---
title: "HW2"
author: "Xiangxiong Feng"
date: "2023-10-02"
output: github_document
---

```{r}
library(tidyverse)
```
# clean the data in pols-month.csv

```{r}
polsmonth_df = 
  read_csv('data/pols-month.csv') |>
  janitor:: clean_names() |>
  separate(mon, into = c('year', 'month'), sep = 4) |>
  separate(month, into = c('month', 'day'), sep = 3) |>
  mutate(
    month = replace(month, month == '-01', 'Jan'),
    month = replace(month, month == '-02', 'Feb'),
    month = replace(month, month == '-03', 'Mar'),
    month = replace(month, month == '-04', 'Apr'),
    month = replace(month, month == '-05', 'May'),
    month = replace(month, month == '-06', 'Jun'),
    month = replace(month, month == '-07', 'Jul'),
    month = replace(month, month == '-08', 'Aug'),
    month = replace(month, month == '-09', 'Sep'),
    month = replace(month, month == '-10', 'Oct'),
    month = replace(month, month == '-11', 'Noc'),
    month = replace(month, month == '-12', 'Dec')
  ) |>
  rename(president = prez_dem) |>
  mutate(
    president = replace(president, president == '0', 'gop'),
    president = replace(president, president == '1', '0'),
    president = replace(president, president == 'gop', '1')
    ) |>
  select(-prez_gop,-day)
  
  
```

# clean data in snp.csv

```{r}
library(lubridate)
library(dplyr)
snp_df = 
  read_csv('data/snp.csv') |>
  janitor::clean_names() |>
  mutate(
    date = parse_date_time(date, order = c('mdy'))) |>
  separate(date, into = c('year', 'month'), sep = 4) |>
  separate(month, into = c('month', 'day'), sep = 3) |>
  mutate(
    month = replace(month, month == '-01', 'Jan'),
    month = replace(month, month == '-02', 'Feb'),
    month = replace(month, month == '-03', 'Mar'),
    month = replace(month, month == '-04', 'Apr'),
    month = replace(month, month == '-05', 'May'),
    month = replace(month, month == '-06', 'Jun'),
    month = replace(month, month == '-07', 'Jul'),
    month = replace(month, month == '-08', 'Aug'),
    month = replace(month, month == '-09', 'Sep'),
    month = replace(month, month == '-10', 'Oct'),
    month = replace(month, month == '-11', 'Noc'),
    month = replace(month, month == '-12', 'Dec')) |>
  select(-day)
  



```




```{r}
unemployment_df = 
  read_csv('data/unemployment.csv') |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = 'month',
    values_to = 'unemployment_rate'
    
  )

  
```




